<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

/** Generated with hyva-csp-helper.php */
?>
<script>
function hyvaCheckoutPaazlWidget() {
    const el = this.$el,
          widgetConfig = JSON.parse(el.dataset.config);

    return {
        init() {
            PaazlCheckout.init(widgetConfig);
        }
    }
}
window.addEventListener('alpine:init', () => Alpine.data('hyvaCheckoutPaazlWidget', hyvaCheckoutPaazlWidget), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>