<?php
/*
 * Copyright © elgentos. All rights reserved.
 * https://elgentos.nl
 */

use Elgentos\HyvaCheckoutPaazl\ViewModel\Shipping\Method\Paazl as PaazlViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var Template $block */

$paazlViewModel = $viewModels->require(PaazlViewModel::class);

$widgetConfig = $paazlViewModel->getWidgetConfig();

?>

<div>
    <div x-data="hyvaCheckoutPaazlWidget"
         data-config="<?= $escaper->escapeHtmlAttr(json_encode($widgetConfig)); ?>">
    </div>
    <div id="widget_paazlshipping_paazlshipping"></div>
</div>
